language: scala
scala: 2.12.8
os: linux

addons:
  apt:
    packages:
    - fakeroot

sudo: false
cache:
  apt: true
  directories:
  - $HOME/.sbt
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.jabba

env:
  global:
  - TRAVIS_JDK=zulu@1.8.212
  - JABBA_HOME=$HOME/.jabba

before_install:
  - $JABBA_HOME/bin/jabba install graalvm@19.0.2
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      export JAVA_HOME="$JABBA_HOME/jdk/graalvm@19.0.2" && export PATH="$JAVA_HOME/bin:$PATH" && java -version;
    elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      export JAVA_HOME="$JABBA_HOME/jdk/graalvm@19.0.2/Contents/Home" && export PATH="$JAVA_HOME/bin:$PATH" && java -version;
    fi
    gu install native-image

jobs:
  include:
    - script: |
        sbt "test" "sailgun-cli/graalvm-native-image:packageBin"
      if: type = pull_request OR (type = push AND branch = master)
      name: "Run tests and test GraalVM Native Image"